### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by x13xDread** [arnav7633/password-manager#3]
Not sure if you care or not but you spelled instead as insteaad in the README.

![image](https://user-images.githubusercontent.com/58883535/138337690-83307e9c-e028-4a8d-9562-1aa11180c10e.png)

**Comment by crackedpotato007** [comment]
Oh my bad I will fix it tomorrow morning

**Comment by crackedpotato007** [comment]
Fixed. Thanks!
